from datetime import datetime
now = datetime.now()
current_time = now.strftime("%H:%M:%S")
print("Current time =", current_time)
key = "unobtained"

print("The Back Story")
t = input("The king has a mission for you. It is to recover a great, lost artifact. Do you accept his mission? (y/n)")
if t == "y":
    print("You set out on this great mission on your horse. Along the path, your map says you have to go along a ")
    print("path to the left. However, the path has a fallen tree blocking the path. You will have to take a detour. ")
else:
    print("After the king hears you declining, he is disgusted by your unwillingness to complete his mission. ")
    print("The king then executes you for disobeying his orders. You spend the last few days thinking about why the ")
    print("hell you turned down his mission. ")
    print("Game Over! ")
    exit()
o = input("The detour path goes near a waterfall connected to a lake. Do you head down the path? (y/n)")
if o == "y":
    print("You head down the path. Near the lake, you hear some of the most beautiful singing you have ever heard. ")
else:
    print("Since you see that the path is blocked, you return to the king and tell him that you could not complete the")
    print("mission due to the blockage. The king then points out the detour path. He then executes you for your ")
    print("stupidity. You spend your last few days wishing you spent more time listening in school. ")
    print("Game Over!")
    exit()
p = input("You have heard of the myths of the sirens, but never really believed them. Do you investigate? (y/n)")
if p == "n":
    print("You ignore the singing, and push forward towards the catacomb. You arrive at the graveyard, at which the ")
else:
    print("You go towards the singing emanating from the lake. All of a sudden, you are grabbed by a tentacle and ")
    print("taken under the water. Your last moment were spent thinking about the fact that you are seriously gullible.")
    print("You are never seen again. ")
    print("Game Over!")
    exit()
w = input("catacomb lies. You find the entrance to the catacomb. It is locked. Do you try to kick the door in? (y/n)")
if w == "n":
    print("Smart you! Instead of kicking the door in, you search the nearby grave-keeper's shed. You find the key")
    print("on a shelf.")
else:
    print("Why did you kick it? You injured your foot doing that! How are you so prone to injury? Also, the door isn't")
    print("even close to being open. ")
    print("Then, a skeleton jumps you. You try to kick his skull off, but with your weakened foot, it barely gets up ")
    print("to his ribs. He then cuts your foot off. He walks off. You slowly bleed to death. Your last moments were ")
    print("spent wishing you had a little more brains than brawns. ")
    exit()
s = input("Pick up the key? (y/n)")
if s == "y":
    key = "obtained"
    print("You picked up the key. You return to the entrance. ")
else:
    print("Not trusting anything in the graveyard, you go to leave, but there are two skeletons guarding the gate from")
    print("which you came. They are wielding spears. You reach to your hip to pull your sword out of its sheath, only")
    print("to grab a fistful of graveyard air. As you look down, you find your sword is missing. You look over")
    print("your shoulder to find a skeleton taunting you with your sword in its hand. It must have pickpocketed it ")
    print("from you as you were deciding whether or not to take the key. It alerts all the other skeletons to your ")
    print("presence. The skeletons close in on you. You think about how bad at perception you are as the skeletons")
    print("beat you to death. Your screams for help are answered by a cold silence. ")
    print("Game Over! ")
    exit()
u = input("Open the door to the catacombs? (y/n)")
if u == "y" and key == "obtained":
    print("You opened the catacomb door! ")
    print("As you enter the door, you nearly fall as you fail to notice a ladder leading down to the catacomb. You ")
    print("look down the drop. ")
else:
    print("As you decide not to risk your life for an artifact, you start climbing the stairs to leave the hallway to")
    print("the entrance of the catacombs, you step on a previously unseen pressure plate. Time seems to slow as you")
    print("realise what you just stepped on. As you are riddled with poison arrows, as the poison seeps into your ")
    print("veins, you really wish that you were born slightly more perceptive. ")
    print("Game Over! ")
    exit()
m = input("There is nothing but darkness in the catacomb. Do you climb down the ladder? (y/n)")
if m == "y":
    print("You sensibly go down the ladder, one rung at a time. Who's a genius? You are!")
    print("You take three steps away from the ladder, when you notice a glimmer in the shadows. You fear it is a")
    print("monster. You attempt to draw your sword, only to find nothing. It must have been pickpocketed by a ")
else:
    print("As you try to turn around to leave, but the slippery floor of the catacomb entrance mans you fall ")
    print("backwards into the catacomb. The fall winds you. A monster in the shadows takes advantage of this, and ")
    print("decapitates you. ")
    print("FATALITY!")
    print("Monster Wins!")
    print("Game over! ")
    exit()
g = input("monster while you were unlocking the door. Investigate the glimmer, even if you are weaponless? (y/n)")
if g == "y":
    print("You cautiously walk towards the glimmer, only to find a long chain, with a fancy spear head adorned on the")
    print("tip. Nice score!")
else:
    print("You ignore the glimmer and move towards the artifact, along a long, thin bridge. You grab it! Mission")
    print("successful! Then, the catacomb is illuminated by a hundred torches. You look down. There are")
    print("massive jagged spikes awaiting you, should you fall off the bridge. The spikes are adorned by countless")
    print("heads of adventurers who came here before you. Then, a masked, cloaked figure drops from the ceiling onto")
    print("the bridge. Since you are weaponless, he easily swipes you off the bridge. Before your head can be")
    print("impaled by the jagged spikes, you wish you were a little bit more gutsy, as maybe the")
    print("thing glimmering in the shadows may have helped you in this situation. You are then impaled.")
    print("Game Over!")
    exit()
k = input("You see the artifact along a long, thin bridge. Do you walk towards the artifact? (y/n)")
if k == "y":
    print("You walk along the bridge and grab the artifact. Nice! The artifact is shaped like a fan, with blades ")
    print("clipped onto it. You turn around to leave, only for the catacomb to be illuminated by many, many torches")
    print("Then, you notice that the bridge is surrounded by a massive drop, which, at the bottom has millions of")
    print("jagged spikes, all adorned with one or two human heads. Then, a masked, cloaked figure drops from ")
    print("the ceiling onto the bridge. He pulls out a pair of sai and doesn't look friendly. The artifact")
    print("also looks like a weapon you could use, but since you need to bring it back to the king, you can't")
else:
    print("You do not trust anything in the catacomb, and turn to leave, even if the king punishes you for")
    print("chickening out. However, when you climb back up the ladder, you find that the door is locked.")
    print("Then, the catacomb lights up, revealing many, many spikes at the bottom. You try all you can to,")
    print("open the door, try attacking it with the chain-spear, kicking it, using the key, nothing works.")
    print("You are stuck in the catacomb for the rest of your days. You last a few weeks before")
    print("becoming extremely weak due to starvation. You consider going towards the artifact, but you cannot bring")
    print("yourself to do it. In your last moments you make a dash for the artifact for a possible escape. ")
    print("However, in your weak state, you lose your footing and fall off the bridge towards the spikes. ")
    print("Before you are impaled, you wish you weren't as cowardly as you were today. You are then impaled. ")
    print("Game Over! ")
    exit()
e = input("use it as a weapon. You do have the chain-spear. Use it? (y/n)")
if e == "y":
    print("You throw the chain spear at him. It impales him in the stomach. You involuntarily pull it back")
    print("towards you, and yell ' Get Over Here! ', and then uppercut him. He goes flying backwards, above")
    print("your head. He painfully lands on the bridge, and springs to his feet almost instantly. He jumps")
    print("up in the air, and disappears. Then, he appears just above your head and kicks you in the face! ")
    print("Impressive kick! When he lands after the kick, you notice that his footing is off. You have a great")
else:
    print("You plead for surrender to the mysterious attacker, or you attempt to. Your surrender attempt either wasn't")
    print("convincing enough, or he wasn't in the mood for it, as he simply swipes your pleading self off the bridge.")
    print("Before you hit the spikes, the attacker taunts you. You open your mouth to scream at him, but you find that")
    print("there is a spike coming out of the front of your mouth, originating from the back of your mouth. You then")
    print("black out from the pain and blood loss. Lesson: Don't attempt to surrender to a mysterious figure. ")
v = input("opportunity to knock him off of the bridge. Do you seize the opportunity? (y/n)")
if v == "y":
    print("You use the chain-spear to sweep his legs. Then, he clumsily falls into the pit. You wave goodbye to him")
    print("before he impacts the spikes. You walk off. You hear the macabre sound of him impacting the spikes as you ")
    print("leave. The graves in the graveyard shake violently. Monsters erupt from the dirt, and close in on you. ")
    print("You instinctually raise your hands in surrender. One of those hands is holding the artifact. ")
    print("However, at one sight of the artifact, the monsters all freeze, and crumble into piles of dust. You leave")
    print("the graveyard and return to the king with the artifact. Then, the king says that you can keep the artifact")
    print("as it is, in fact a weapon, as a reward. You go on to be the most feared knight in the kings army for your")
    print("expertise with the fan blades. Your fellow knights go on to nickname you 'Kitana'. Surprisingly, the blades")
    print("also provide the wielder with immunity to aging, so you go and retire from being a knight, and you are")
    print("allowed to keep the fan blade. You then go on to live a happy life, for all of eternity and time.")
    print("You Win!")
    exit()
else:
    print("You stand there, not taking advantage of the opportunity given to you. He starts getting closer. You try")
    print("to do the chain-spear throw again ,but nothing happens. You panic. He gets so close, that he can throw you")
    print("off the side of the bridge, which he does. Mid-fall, and as the air rushes past you, you think about what")
    print("your future could have looked like if you had just swept his legs. Then, you collide with the spikes. ")
    print("You have a few more seconds to think before you bleed out. Your last thought is about how close you were to")
    print("the end. You then die. ")
    print("Game Over!")
    exit()